# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: thePaulista
email: hedywoo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "when you don't create things, you become defined by your tastes rather than ability. your tastes only narrow & exclude people. so create" _why the lucky stiff
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thepaulista.github.io" # the base hostname & protocol for your site
github_username: thePaulista 

# Build settings
markdown: kramdown
permalink: pretty
  
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000



