# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: thePaulista
email: hedywoo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "when you don't create things, you become defined by your tastes rather than ability. your tastes only narrow & exclude people. so create" _why the lucky stiff
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thepaulista.github.io" # the base hostname & protocol for your site
github_username: thePaulista 
paginate: 4

# Build settings
markdown: kramdown #converts md to html
permalink: pretty #removes the .html at the end of the url, only shows the title


#google analytics 
google_analytics: true
tracking_id: UA-73012002-2 #  google analytics tracking id

sass:
  style:   compressed
  sass_dir:   _sass

gems:
    - jekyll-paginate
comments: true




